# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "850e0e4c48e4c1cc19590f2029799851"
name = "test-cli"
handle = "test-cli-55"
application_url = "https://wales-controversy-city-indicated.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-e75e89bd.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://wales-controversy-city-indicated.trycloudflare.com/auth/callback",
  "https://wales-controversy-city-indicated.trycloudflare.com/auth/shopify/callback",
  "https://wales-controversy-city-indicated.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
